In [1]:
import numpy as np

In [10]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
arr[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [19]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])